name: CI Pipeline
on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Add MinGW-w64 to PATH
        run: echo PATH=%ProgramData%\chocolatey\lib\mingw\tools\install\mingw64\bin;%PATH%>>%GITHUB_ENV%
        shell: cmd
      - name: Build and run tests
        run: ./script/build.bat
        shell: cmd
      - name: Upload webview.dll
        uses: actions/upload-artifact@v2
        with:
          name: webview_${{github.sha}}
          path: D:\a\webview\webview\dll\x64\webview.dll        
